site_name: Argonne Onboarding Guide
site_url: https://argonne-lcf.github.io/student-onboarding/

theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest
    - header.autohide

  features:
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.tracking
  palette:
  # Auto
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: alcf
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-night
      name: Switch to system preference

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: /faq-guidance/faq/

    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/argonne-leadership-computing-facility/

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/argonne.lcf/

    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/argonne.lcf/

    - icon: fontawesome/brands/flickr
      link: https://www.flickr.com/people/argonne/

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@argonneleadershipcomputing8396

    - icon: fontawesome/brands/x-twitter
      link: https://x.com/argonne_lcf?lang=en

  favicon: images/favicon.svg

extra_css:
  - css/style.css

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md

  - Pre-hire Tasks: 
    - Tech Setup: pre-hire-tasks/tech-setup.md
    - Forms: pre-hire-tasks/forms.md

  - Orientation:
    - New-Hire Orientation: orientation/new-hire-orientation.md
    - Arriving at Argonne: orientation/arriving.md
    - Training: orientation/training.md

  - Websites & Tools: websites-tools/index.md

  - Housing & Travel: 
    - Living Accommodations: housing-travel/accommodations.md
    - Travel: housing-travel/travel.md

  - Campus Life:
    - Learning Opportunities: campus-life/learning.md
    - Clubs & Activities: campus-life/activities.md
    - Dining: campus-life/dining.md

  - FAQ & Guidance: 
    - FAQ: faq-guidance/faq.md
    - Guidance: faq-guidance/guidance.md

